### ISSUE TITLE
Error running locally

### ISSUE THREAD

**Issue by otakustay** [Acidic9/emotion-solid#2]
I was preparing to contribute some features to this package but encountered some issues.

I've forked this repo and tried to add a simple demo in it, however when my demo component uses `import { styled } from '../src'` it fails to run with a console warnign:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'as')
```

Corresponding code is at [line 82 of base.tsx](https://github.com/otakustay/emotion-solid/blob/d006bb4f5fa54a96ced1c054104e7aa40943f65c/src/base.tsx#L82):

When I build this package first and change my import statement to `import { styled } from '../dist/index.esm.js'` it works without any issue.

Not sure why the unbuilt version is crashing so I have to ask here. My fork is here: https://github.com/otakustay/emotion-solid

**Comment by Acidic9** [comment]
Hm that's strange, it sounds like it's trying to parse typescript as JavaScript.. I'll have a look into this today

**Comment by otakustay** [comment]
I tried deleting `yarn.lock` and have a fresh install, with disabling hot reload in `vite.config.ts` it works, still figuring out why hot reload crashes it.

**Comment by otakustay** [comment]
It seems a bug inside solid-js, I've created an issue to track it: https://github.com/solidjs/solid/issues/744
